### ISSUE TITLE
Improve Card Sets Pages

### ISSUE THREAD

**Issue by kingcons** [TIY-ATL-ROR-2016-Feb/planeswalkr#10]
Users should be able to visit a Card Sets index to see all available card sets. Clicking on one should take them to the show page. Maybe we should consider having a paginated spoiler view as well as a listing view where images display when you hover over the card name.

**Comment by kingcons** [comment]
Dave and Jen are pairing on card sets!

**Comment by jennifercford** [comment]
please explain further on on paginated spoiler veiw
